name: tse_2026_elt
version: '1.0.0'
config-version: 2
profile: tse_2026_elt
model-paths: ["dbt/models"]
macro-paths: ["dbt/macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
models:
  tse_2026_elt:
    +materialized: table
